### ISSUE TITLE
console.log(document) is not same as in devtools

### ISSUE THREAD

**Issue by krishnagogada** [webextensions/console-panel#1]
When I write `console.log (document)` in the console-panel the output is like 
![image](https://user-images.githubusercontent.com/54623105/106088276-b01c0580-614b-11eb-93d3-ae3d2b1c0098.png)

but in devtools 

![image](https://user-images.githubusercontent.com/54623105/106088358-d5107880-614b-11eb-9dc1-700746d7eaac.png)

What is the reason in console-panel not as same in devtools, how can I get expected output?
TIA

**Comment by webextensions** [comment]
**Probably you can use `console.log(document.documentElement);` and it might suffice your requirements.**

The `document` has a special nodeType of its own (`Node.DOCUMENT_NODE = 9`) (Ref: https://developer.mozilla.org/en-US/docs/Web/API/Node/nodeType).

For browsers, it makes sense to add appropriate handling for `console.log(document)`.
For this tool, handling has been added for `HTMLElement` and `Text` and various other kind of entries, but `HTMLDocument` does not have a special handling yet. And any such unhandled nodeType or special object is treated as a regular object and hence you see the above mentioned behavior.

While it would be possible to add such handling, but probably it is fine to keep that out of scope for now.

To review the types which are being handled (and which aren't), you can have a quick look at https://github.com/webextensions/console-panel/blob/f7ba215b0ecf51dcbd3d78cb425f55c790afd4b7/src/console-panel.js#L958

Marking it closed since the above mentioned workaround should cover for the requirements.
